### ISSUE TITLE
REE/ EoF for pure states

### ISSUE THREAD

**Issue by exAClior** [numqi/numqi#4]
Need to implement REE / EoF for pure states [arxiv-link0](https://arxiv.org/abs/2009.04982) [arxiv-link1](https://arxiv.org/abs/quant-ph/0409009)

**Comment by husisy** [comment]
#30 relative entropy of entanglement (REE) for pure states

**Comment by husisy** [comment]
Entanglement of Formation (EoF) for pure states is implemeneted at `numqi.entangle.get_eof_pure()`
